language: python
env:
  - DJANGO="20"
  - DJANGO="21"
  - DJANGO="master"
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade pip setuptools tox pipenv
  - pipenv install
script:
  - tox -e py$(python -c 'import sys;print("".join(map(str, sys.version_info[:2])))')-dj${DJANGO}
matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO="master"
