# Generated by Django 2.1.2 on 2018-10-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('txn_ids', models.TextField()),
                ('txn_affected', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
