# Generated by Django 2.1.2 on 2018-10-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='txn_affected',
            new_name='txns_affected',
        ),
    ]
