# Generated by Django 2.1.2 on 2018-10-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20181011_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='account_id',
            field=models.CharField(default='acc_00009OgJFR1Oo2tQQFaWOX', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='action',
            field=models.CharField(default='tag_apply', max_length=20),
            preserve_default=False,
        ),
    ]
