# Generated by Django 2.1.2 on 2018-10-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20181011_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
